""" DNS services """

# TODO: url = "/api/v1/services/dnsmasq"
# TODO: url = "/api/v1/services/dnsmasq/apply"
# TODO: url = "/api/v1/services/dnsmasq/host_override"
# TODO: url = "/api/v1/services/dnsmasq/host_override/alias"
# TODO: url = "/api/v1/services/dnsmasq/restart"
# TODO: url = "/api/v1/services/dnsmasq/start"
# TODO: url = "/api/v1/services/dnsmasq/stop"

# TODO: url = "/api/v1/services/unbound"
# TODO: url = "/api/v1/services/unbound/access_list"
# TODO: url = "/api/v1/services/unbound/access_list/row"
# TODO: url = "/api/v1/services/unbound/apply"
# TODO: url = "/api/v1/services/unbound/host_override"
# TODO: url = "/api/v1/services/unbound/host_override/alias"
# TODO: url = "/api/v1/services/unbound/restart"
# TODO: url = "/api/v1/services/unbound/start"
# TODO: url = "/api/v1/services/unbound/stop"
